package com.games.java.model.players.corba.idls.registry;


/**
* com/games/java/model/players/corba/idls/registry/RegistryFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/games/java/model/players/corba/idls/Regestry.idl
* 18 декабря 2016 г. 19:18:29 MSK
*/

public interface RegistryFactoryOperations 
{
  void registry (com.games.java.model.players.corba.idls.game.Player player);
  String getPlayerOne ();
  String getPlayerEnemy ();
} // interface RegistryFactoryOperations
