package game;

/**
* game/CoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 14:50:36 MSK
*/

public final class CoreHolder implements org.omg.CORBA.portable.Streamable
{
  public game.Core value = null;

  public CoreHolder ()
  {
  }

  public CoreHolder (game.Core initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = game.CoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    game.CoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return game.CoreHelper.type ();
  }

}
