package game;


/**
* game/FieldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 14:50:36 MSK
*/

public interface FieldOperations 
{
  game.Core coreNext ();
  void startGame ();
  int getCountCores ();
  void stopGame ();
  void setPlayerOne (game.Player player);
  void setPlayerEnemy (game.Player player);
} // interface FieldOperations
