package com.games.java.model.players.corba.idls.game;

/**
* com/games/java/model/players/corba/idls/game/CoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/games/java/model/players/corba/idls/Regestry.idl
* 18 декабря 2016 г. 19:18:29 MSK
*/

public final class CoreHolder implements org.omg.CORBA.portable.Streamable
{
  public com.games.java.model.players.corba.idls.game.Core value = null;

  public CoreHolder ()
  {
  }

  public CoreHolder (com.games.java.model.players.corba.idls.game.Core initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.games.java.model.players.corba.idls.game.CoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.games.java.model.players.corba.idls.game.CoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.games.java.model.players.corba.idls.game.CoreHelper.type ();
  }

}
