package com.games.java.model.players.corba.idls.game;


/**
* com/games/java/model/players/corba/idls/game/CoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 19:29:54 MSK
*/

public interface CoreOperations 
{
  com.games.java.model.players.corba.idls.game.SizeCore getSize ();
  void setSize (com.games.java.model.players.corba.idls.game.SizeCore size);
  com.games.java.model.players.corba.idls.game.Point2D getLocation ();
  void setLocation (com.games.java.model.players.corba.idls.game.Point2D location);
  int getId ();
  void setId (int id);
  int getCountPhage ();
  void setCountPhage (int countPhage);
  void updateCores (com.games.java.model.players.corba.idls.game.Core sourceCore);
  com.games.java.model.players.corba.idls.game.StateCore getState ();
} // interface CoreOperations
