package com.games.java.model.players.corba.idls.game;


/**
* com/games/java/model/players/corba/idls/game/Core.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/games/java/model/players/corba/idls/Regestry.idl
* 18 декабря 2016 г. 11:38:08 MSK
*/

public interface Core extends CoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Core
