package com.games.java.model.players.corba.idls.game;


/**
* com/games/java/model/players/corba/idls/game/FieldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 19:29:54 MSK
*/

public interface FieldOperations 
{
  com.games.java.model.players.corba.idls.game.Core coreNext (int i);
  void startGame ();
  int getCountCores ();
  void stopGame ();
  void setPlayerOne (com.games.java.model.players.corba.idls.game.Player player);
  void setPlayerEnemy (com.games.java.model.players.corba.idls.game.Player player);
} // interface FieldOperations
