package com.games.java.model.players.corba.idls.game;


/**
* com/games/java/model/players/corba/idls/game/PlayerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/games/java/model/players/corba/idls/Regestry.idl
* 18 декабря 2016 г. 19:18:29 MSK
*/

public interface PlayerOperations 
{
  void calculateChanges (com.games.java.model.players.corba.idls.game.Core core);
  void updateCoreView (com.games.java.model.players.corba.idls.game.Core core);
  void setFieldName (String name);
  String getFieldName ();
  com.games.java.model.players.corba.idls.game.StateCore getState ();
} // interface PlayerOperations
