package com.games.java.model.players.corba.idls.game;


/**
* com/games/java/model/players/corba/idls/game/Point2D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/games/java/model/players/corba/idls/Regestry.idl
* 18 декабря 2016 г. 19:18:29 MSK
*/

public interface Point2D extends Point2DOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Point2D
