package com.games.java.model.players.corba.idls.game;


/**
* com/games/java/model/players/corba/idls/game/Point2D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 19:29:54 MSK
*/

public interface Point2D extends Point2DOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Point2D
