package com.games.java.model.players.corba.game;


/**
* com/games/java/model/players/corba/game/FieldHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 19:29:30 MSK
*/

abstract public class FieldHelper
{
  private static String  _id = "IDL:game/Field:1.0";

  public static void insert (org.omg.CORBA.Any a, com.games.java.model.players.corba.game.Field that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.games.java.model.players.corba.game.Field extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.games.java.model.players.corba.game.FieldHelper.id (), "Field");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.games.java.model.players.corba.game.Field read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FieldStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.games.java.model.players.corba.game.Field value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.games.java.model.players.corba.game.Field narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.games.java.model.players.corba.game.Field)
      return (com.games.java.model.players.corba.game.Field)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.games.java.model.players.corba.game._FieldStub stub = new com.games.java.model.players.corba.game._FieldStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.games.java.model.players.corba.game.Field unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.games.java.model.players.corba.game.Field)
      return (com.games.java.model.players.corba.game.Field)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.games.java.model.players.corba.game._FieldStub stub = new com.games.java.model.players.corba.game._FieldStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
