package com.games.java.model.players.corba.game;

/**
* com/games/java/model/players/corba/game/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 19:29:30 MSK
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.games.java.model.players.corba.game.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (com.games.java.model.players.corba.game.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.games.java.model.players.corba.game.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.games.java.model.players.corba.game.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.games.java.model.players.corba.game.PlayerHelper.type ();
  }

}
