package com.games.java.model.players.corba.game;


/**
* com/games/java/model/players/corba/game/Point2DOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Tmp/Desktop/computer/lening/netCreacer/distributedSystem/WarPhage/implementation/src/com/games/java/model/players/corba/idls/Regestry.idl
* 23 декабря 2016 г. 19:29:30 MSK
*/

public interface Point2DOperations 
{
  double getX ();
  void setX (double x);
  double getY ();
  void setY (double y);
} // interface Point2DOperations
