module game{

  enum SizeCore{ BIG_CORE, SMALL_CORE };
  enum StateCore{ RED, GREEN, BLACK };

  interface Point2D{

     double getX();
     void setX(in double x);
     double getY();
     void setY(in  double y);

  };

  interface Core{

     SizeCore getSize();
     void setSize(in SizeCore size);
     Point2D getLocation();
     void setLocation(in Point2D location);
     unsigned long getId();
     void setId(in unsigned long id);
     unsigned long getCountPhage();
     void setCountPhage(in unsigned long countPhage);
     void updateCores(in Core sourceCore);
     StateCore getState();

  };

  interface Player{

     void calculateChanges(in Core core);
     void updateCoreView(in Core core);

     void setPlayerName(in wstring name);
     wstring getPlayerName();

     void setState(in StateCore state);
     StateCore getState();

     void setFieldName(in wstring name);
     wstring getFieldName();


  };

  interface Field{

            Core coreNext(in unsigned long i);
            void startGame();
            unsigned long getCountCores();
            void stopGame();

            void setPlayerOne(in Player player);
            void setPlayerEnemy(in Player player);
  };

};


module registry{
 interface RegistryFactory{

    void registry(in game::Player player);
    wstring getCurrentName();
    wstring getPlayerOne();
    wstring getPlayerEnemy();
 };
};